### ISSUE TITLE
wheelpatcher doesn't work

### ISSUE THREAD

**Issue by Raphi-2Code** [PaologGithub/UrsinaForMobile#5]
Renaming original wheel ursina-7.0.0-py3-none-any.whl -> ursina-7.0.0-py3-none-any.whl.non_patched
Traceback (most recent call last):
  File "wheelpatcher.py", line 72, in <module>
    rename_cpython_so_in_whl(whl_path)
  File "wheelpatcher.py", line 13, in rename_cpython_so_in_whl
    os.rename(original_whl_path, non_patched_whl_path)
FileNotFoundError: [WinError 2] The system cannot find the specified file: 'ursina-7.0.0-py3-none-any.whl' -> 'ursina-7.0.0-py3-none-any.whl.non_patched' 

When executing the wheelpatcher.py with python3.8 for any file (here ursina)

**Comment by Raphi-2Code** [comment]
and this even happens when using the absolute file path

**Comment by Raphi-2Code** [comment]
and you only added wheels with .so, but when using windows, you need .pyd wheels

**Comment by PaologGithub** [comment]
> Renaming original wheel ursina-7.0.0-py3-none-any.whl -> ursina-7.0.0-py3-none-any.whl.non_patched Traceback (most recent call last): File "wheelpatcher.py", line 72, in rename_cpython_so_in_whl(whl_path) File "wheelpatcher.py", line 13, in rename_cpython_so_in_whl os.rename(original_whl_path, non_patched_whl_path) FileNotFoundError: [WinError 2] The system cannot find the specified file: 'ursina-7.0.0-py3-none-any.whl' -> 'ursina-7.0.0-py3-none-any.whl.non_patched'
> 
> When executing the wheelpatcher.py with python3.8 for any file (here ursina)

You don't need to wheelpatch the ursina.whl file
